ExoErrorHandler/Controllers/IssueErrorController.cs
using BAL.Interface;
using BAL.Services;
using MODEL;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ExoErrorHandler.Controllers
{
    public class IssueErrorController : Controller
    {
        // GET: IssueError
        IErrorHandlerServices _iErrorHandlerServices;

        public IssueErrorController()
        {
            _iErrorHandlerServices = new ErrorHandlerServices();

        }
        public ActionResult Index()
        {
            ViewBag.OrganizationSelectList = new SelectList(_iErrorHandlerServices.getOrganizationList(), "OrganizationId", "OrganizationName");
            ViewBag.DeveloperSelectList = new SelectList(_iErrorHandlerServices.getDeveloperList(), "UserId", "FullName");

            return View();
        }
        public ActionResult AddIssue(IssueErrorView modl)
        {
            string imagePath = SaveFile(modl.Image);
            modl.ImagePath = imagePath;
            _iErrorHandlerServices.SaveIssueError(modl);
            return RedirectToAction("Index");

        }

        public string SaveFile(HttpPostedFileBase File)
        {
            //Use Namespace called :  System.IO  
            string FileName = Path.GetFileNameWithoutExtension(File.FileName);

            //To Get File Extension  
            string FileExtension = Path.GetExtension(File.FileName);

            //Add Current Date To Attached File Name  
            FileName = Guid.NewGuid().ToString().Substring(0, 4) + "-" + FileName.Trim() + FileExtension;

            //Get Upload path from Web.Config file AppSettings.  
            //  string UploadPath = ConfigurationManager.AppSettings["UserImagePath"].ToString();
            var UploadPath = Path.Combine(Server.MapPath("~/Content/Upload"), FileName);

            //Its Create complete path to store in server.  
            var imgPath = UploadPath;

            //To copy and save file into server.  
            File.SaveAs(imgPath);

            string fPath = "/Content/Upload/" + FileName;
            return (fPath);
        }



    }
}

ExoErrorHandler/Views/IssueError/Index.cshtml
@model MODEL.IssueErrorView

@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm("AddIssue", "IssueError", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary();

    @*<div class="container">
        <div class="row justify-content-md-center">
            <div class="col col-lg-4">
                @Html.DisplayNameFor(model => model.OrganizationName):
                @Html.DropDownListFor(m => m.OrganizationId, ViewBag.OrganizationSelectList as SelectList, "--SELECT ORGANIZAION--", new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.OrganizationId, "", new { @class = "text-danger" })
            </div>
            <div class="col col-lg-4">
                @Html.DisplayNameFor(model => model.ProjectName)::
                @Html.DropDownListFor(m => m.ProjectId, new SelectList(""), "--SELECT PROJECT--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
            </div>
            <div class="col col-lg-4">
                @Html.DisplayNameFor(model => model.ModuleName)
                @Html.DropDownListFor(m => m.ModuleId, new SelectList(""), "--SELECT MODULE--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModuleName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row justify-content-md-center mb-3">
            <div class="col col-lg-4">
                @Html.DisplayNameFor(model => model.ModuleName)
                @Html.DropDownListFor(m => m.ModuleId, new SelectList(""), "--SELECT MODULE--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModuleName, "", new { @class = "text-danger" })
            </div>

            <div class="col col-lg-4 mb-3">
                <input type="file" id="Image" name="Image" />
            </div>
            <div class="col col-lg-4">
                <img id="showImage" src="" alt="" height=180 width=200 />
            </div>
        </div>
    </div>*@
    <div class="container">



        <div class="mb-3">

            @Html.DisplayNameFor(model => model.OrganizationName)::
            @Html.DropDownListFor(m => m.OrganizationId, ViewBag.OrganizationSelectList as SelectList, "--SELECT ORGANIZAION--", new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.OrganizationId, "", new { @class = "text-danger" })
        </div>
        <div class="mb-3">

            @Html.DisplayNameFor(model => model.ProjectName)::
            @Html.DropDownListFor(m => m.ProjectId, new SelectList(""), "--SELECT PROJECT--", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
        </div>
        <div class="mb-3">

            @Html.DisplayNameFor(model => model.ModuleName)
            @Html.DropDownListFor(m => m.ModuleId, new SelectList(""), "--SELECT MODULE--", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ModuleName, "", new { @class = "text-danger" })

        </div>
        <div class="mb-3">

            @Html.DisplayNameFor(model => model.FullName)
            @Html.DropDownListFor(m => m.UserId, ViewBag.DeveloperSelectList as SelectList, "--SELECT Developer--", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })

        </div>
        <div class="mb-3">
            <input type="file" id="Image" name="Image" />
        </div>

        <div class="mb-3">
            <img id="showImage" src="~/Content/Upload/noimg.jpeg" alt="" height=180 width=200 />
        </div>

        <div class="mb-3">
            @Html.DisplayNameFor(model => model.ErrorDescription)
        </div>

        <div class="mb-3">
            @Html.TextAreaFor(m => m.ErrorDescription, 8, 100, new { @class = "required" })
            @Html.ValidationMessageFor(model => model.ErrorDescription, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Upload</button>
        </div>


    </div>


}






@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('#Image').change(function () {
                //$(this).get(0).files[0] and this.files[0] are the same thing both return the  current file object'
                var file = this.files[0];
                var url = window.URL.createObjectURL(this.files[0]);
                $('#showImage').attr("src", url);
            });

            //$('#form1').submit(function (event) {
            //    event.preventDefault();
            //
            //    var formData = new FormData($(this)[0]);

            //    $.ajax({
            //        url: '/IssueError/AddIssue',
            //        type: 'POST',
            //        data: formData,
            //        cache: false,
            //        contentType: false,
            //        processData: false,
            //        success: function (data) {
            //            console.log(data);
            //            console.log("success");
            //        },
            //        error: function (xhr, textStatus, errorThrown) {
            //            console.log(xhr.responseText);
            //        }
            //    });
            //});



            $("#OrganizationId").change(function () {

                $.get("/Module/GetProjectByOrganizationId", { organizationId: $("#OrganizationId").val() }, function (data) {
                    $("#ProjectId").empty();
                    $("#ProjectId").append("<option>--SELECT PROJECT--</option>")

                    $.each(data, function (index, row) {
                        $("#ProjectId").append("<option value='" + row.ProjectId + "'>" + row.ProjectName + "</option>")
                    });
                });
            });

            $("#ProjectId").change(function () {

                console.log("test1");

                $.get("/Module/GetModuleByProjectId", { organizationId: $("#OrganizationId").val(), projectId: $("#ProjectId").val() }, function (data) {
                    console.log("test33");
                    $("#ModuleId").empty();
                    $("#ModuleId").append("<option>--SELECT MODULE--</option>")

                    $.each(data, function (index, row) {

                        $("#ModuleId").append("<option value='" + row.ModuleId + "'>" + row.ModuleName + "</option>")
                    });
                });
            });
        });

    </script>
}